Completed and (more or less) styled LOS and Hourly tables
ardium-pl/sortech-ncbr pull request #7
Opened 2024-08-06 10:33 UTC by Szymon-Skowron

- LOS and hourly tables now have logic resembling formulas from the Excel spreadsheet
- static table is currently hardcode - its logic and styling will be added later

2024-08-06 10:37 UTC, Szymon-Skowron commented on src/app/hourly-data.service.ts
> +  readonly currentDayOfWeek: keyof Dzien = 'poniedzialek';
Nie wiem czemu tutaj nie działa to keyof Dzien. Poperty names interface'u dzien to stringi z nazwami tygodnia, chcialem zeby currentDayOfWeek mogło być właśnie jedynie takimi nazwami. Obecnie moge tam wpisac cokolowiek i nie wywala, żadnego bledu.

2024-08-06 13:38 UTC, joker876 requested changes
Poza szczegółowymi komentarzami, do projektu należy też doinstalować `prettier`, zdefiniować plik `.prettierrc` (przekopiować z repo GWW-Legal), stworzyć skrypt do formatiowania plików (też przekopiować, z pliku `package.json` w głównym folderze), a na koniec sformatować wszystkie pliki

2024-08-06 13:38 UTC, joker876 commented on src/app/static-table/static-table.component.ts
> +  ];
Wszystkie te informacje się nie zmieniają, więc najlepiej jakby były w osobnym pliku. Szkoda zaśmiecać komponent setkami linijek kodu które nic dla komponentu nie znaczy. W komponencie tylko zaimportować tą zmienną z nowego pliku i przypisać do pola.

A swoją drogą to pola które się nigdy nie zmieniają powinny być zawsze `readonly`, a zmienne powinny być `const` i zapisane `CONSTANT_CASE`.

2024-08-06 13:38 UTC, joker876 commented on src/app/static-table/static-table.component.scss
> +  // --ag-header-background-color: rgb(209, 64, 129);
Stary zakomentowany kod do usunięcia.

2024-08-06 13:38 UTC, joker876 commented on src/app/los-data.service.ts
> +  ];
Domyślam się że to są tylko tymczasowe rzeczy, ale i tak fajnie jakby były w osobnym pliku.

2024-08-06 13:38 UTC, joker876 commented on src/app/length-of-stay/length-of-stay.component.scss
> +  // --ag-header-background-color: rgb(209, 64, 129);
Stary kod do usunięcia

2024-08-06 13:38 UTC, joker876 commented on src/app/interfaces/summaries.ts
> +  // mozliwoscPokryciaZopatrzenia: null;
Stary kod do usunięcia (chyba że na 100% będzie w przyszłości coś stąd używane)

2024-08-06 13:38 UTC, joker876 commented on src/app/interfaces/summaries.ts
Po co w tych wszystkich interfejsach są `[property: string]: string | number | null;`? Jakieś dynamicznie tworzone pola będą?

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-table/hourly-table.component.ts
> +    // autoHeight: true,
Stary kod do usunięcia

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-table/hourly-table.component.scss
> +  // --ag-header-column-separator-color: black;
Stary kod do usunięcia

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-table/col-defs-hourly.ts
Stary kod do usunięcia - wiele takich przypadków w tym pliku, nie będę komentował każdego

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-data.service.ts
> +  readonly currentDayOfWeek: keyof Dzien = 'poniedzialek';
`keyof Dzien` zwraca klucze jakie są w tym interfejsie. Interfejs wygląda tak:
![image](https://github.com/user-attachments/assets/6cf45d38-c64b-41b1-a3ce-6f9d5ac41bbc)

Więc efektem `keyof Dzien` będzie typ:
```ts
keyof Dzien === 'poniedzialek' | 'wtorek' | 'sroda' | 'czwartek' | 'piatek' | 'sobota' | 'niedziela' | string
```

Na końcu widać `string`, więc taki typ przyjmie wszystko. A teraz zadanie dla ciebie: dlaczego?

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-data.service.ts
> +  // }
Stary kod do usunięcia

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-data.service.ts
> +  // }
Stary kod do usunięcia

2024-08-06 13:38 UTC, joker876 commented on src/app/hourly-data.service.ts
> +  readonly currentDayOfWeek: keyof Dzien = 'poniedzialek';
A wszystkiego tego można by uniknąć, gdyby przechowywać dni jako `number`....

0 = niedziela, 1 = poniedzialek, ..., 6 = sobota i po sprawie

2024-08-06 13:38 UTC, joker876 commented on src/app/constants.ts
> +  },
Godziny dod zamiany na minuty

2024-08-06 13:38 UTC, joker876 commented on src/app/constants.ts
> +  },
Jakoś lepiej to pole trzeba nazwać, bo z taką nazwą nie mam pojęcia co to są za liczby

2024-08-06 13:38 UTC, joker876 commented on src/app/constants.ts
> +  },
Tak samo z tą nazwą, też nie wiadomo o co chodzi

2024-08-06 13:38 UTC, joker876 commented on src/app/app.component.ts
> +  selectedTabIndex = 1;
indeks nie jest zmieniany, więc `readonly`, i najlepiej zmienić nazwę na coś typu `defaultSelectedTabIndex`

2024-08-06 13:38 UTC, joker876 commented on src/app/app.component.html
> +  >
Nie potrzebne jest dodawanie templatów do każdego labela. Zamiast tego zmienić w komponencie `encapsulation` na `ViewEncapsulation.None` (artykuł: https://frontendinterviewquestions.medium.com/what-is-view-encapsulation-in-angular-921388260620)

2024-08-06 13:38 UTC, joker876 commented on angular.json
> +      },
Przekopiuj pole `schematics` z repo inwentaryzacji

2024-08-06 21:08 UTC, joker876 commented on src/app/length-of-stay/col-defs-los.ts
> +}
Nie zauważyłem tego wcześniej, ale tutaj nie ma potrzeby tworzenia zupełnie nowej funkcji, jeśli można użyć jednej z wielu bibliotek która już posiada taką funkcję.

Proponuję np. bibliotekę `more-rounding` https://www.npmjs.com/package/more-rounding
ewentualnie jest też taka funkcja w popularnej bibliotece `lodash`

2024-08-06 21:14 UTC, joker876 requested changes

2024-08-06 21:14 UTC, joker876 commented on src/app/static-data.service.ts
> +      rows[7].procPacjentow! * rows[7].lozkoObserwacja!;
matko ile powtórzeń... pętla proszę! I to tylko jedna!

2024-08-06 21:14 UTC, joker876 commented on src/app/static-table/col-defs-static.ts
> +}
Tutaj to samo. Użyć biblioteki!

2024-08-06 21:14 UTC, joker876 commented on src/app/static-table/static-table.component.ts
> +  readonly rowData = computed(() => this.staticDataService.rowData());
rowData można zdefiniować znacznie prościej: po prostu przypisać sygnał bezpośrednio:
```ts
readonly rowData = this.staticDataService.rowData;
```
(zauważ że bez wywołania sygnału za pomocą `()`)

2024-08-06 21:14 UTC, joker876 commented on src/app/static-table/static-table.component.ts
> +    this.staticDataService.applyRowCalculations(this.rowData(), changeRow);
Albo dać do jednej linijki, albo zmienić `let` na `const`, które wolisz

2024-08-11 23:53 UTC, Szymon-Skowron commented on src/app/static-table/static-table.component.ts
> +  readonly rowData = computed(() => this.staticDataService.rowData());
I wtedy rowData będzie działało tak samo jakby było tym computed signal? Jeśli tak, to rozumiem, że analogicznie definicje rowData w innych komponentach zmienić.

2024-08-11 23:57 UTC, Szymon-Skowron commented on src/app/hourly-table/hourly-table.component.ts
> +    // autoHeight: true,
Usunę komentarze dot. headerów jak zaakceptujesz ich wygląd

2024-08-11 23:58 UTC, Szymon-Skowron commented on src/app/hourly-table/col-defs-hourly.ts
Tam są zakomentowane definicje kolumn, jeszcze nie wiem czy one na pewno będą do usunięcia.

2024-08-12 00:03 UTC, Szymon-Skowron commented on src/app/constants.ts
> +  },
Te dane dot. shardcodowanych w Excel'owym pliku rozkładów. Nie wiem jak ostatecznie ustaliliście z Mikołajem, ale wydaje mi się, że będziecie te informacje trzymać w bazie danych, więc ten kod prawdopodobnie będzie to usunięcia.
![obraz](https://github.com/user-attachments/assets/9e3dd71d-4a4b-4a87-b6bb-4295f3b11fd9)

2024-08-12 00:04 UTC, Szymon-Skowron commented on src/app/constants.ts
> +  },
(jak wyżej)
Te dane dot. shardcodowanych w Excel'owym pliku rozkładów. Nie wiem jak ostatecznie ustaliliście z Mikołajem, ale wydaje mi się, że będziecie te informacje trzymać w bazie danych, więc ten kod prawdopodobnie będzie to usunięcia.
![obraz](https://github.com/user-attachments/assets/bf46019a-0df7-4cca-a261-2b239ee556e5)

2024-08-12 00:14 UTC, Szymon-Skowron commented on src/app/hourly-data.service.ts
> +  readonly currentDayOfWeek: keyof Dzien = 'poniedzialek';
Informacje na temat tego jaki był dzień tygodnia (czy był to poniedziałek, wtorek itp.) potrzebuje do obliczania potem danych w komórkach tabeli, nie wiem czy potrzebujemy taką informacje trzymać jeszcze dodatkowo w bazie danych czy z twojego date pickera to dam rade wyciągać.

2024-08-15 10:25 UTC, Szymon-Skowron commented on src/app/constants.ts
> +  },
Robiłem wszystkie te formuły 1:1 tak jak u nich w Excelu. Kod, który to zaznaczyłeś jest równoważny z wartościami ostatniego rzędu tabeli na screenshocie. Te wartości sa dalej potrzebne do obliczania komórek tabel. Skoro oni mieli tak te wartości podane u siebie, to jak tez tak zrobiłem.
![image](https://github.com/user-attachments/assets/31aaa326-d1fa-4d1c-ba4a-3f93cbeb62c4)

2024-08-17 14:54 UTC, joker876 approved these changes

2024-08-17 14:55 UTC, merged